server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: docker_socket
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
      filters:
        - name: label
          values: ['logging=promtail']
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container_name'
    - source_labels: ['__meta_docker_container_id']
      target_label: 'container_id'
    - source_labels: ['__meta_docker_container_log_stream']
      target_label: 'stream'
    - source_labels: ['__meta_docker_container_label_com_docker_compose_image']
      regex: 'sha256\:(.*)'
      target_label: 'image_id'
