http:
  routers:
    nextcloud:
      rule: 'Host(`cloud.{{ env "HOST" }}`)'
      entryPoints:
        - webSecure
      service: nextcloud

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:11000" # Use the host's IP address if Traefik runs outside the host network
