http:
  routers:
    router-web-panel:
      rule: 'Host(`router.{{ env "HOST" }}`)'
      entryPoints:
        - webSecure
      service: router-web-panel
      middlewares: authelia

  services:
    router-web-panel:
      loadBalancer:
        servers:
          - url: "http://router"
