http:
  middlewares:
    authelia:
      forwardauth:
        address: 'http://authelia:9091/api/verify?rd=https://auth.{{ env "HOST" }}'
        trustForwardHeader: true
        authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
    secure-headers:
      headers:
        # hostsProxyHeaders:
        #   - "X-Forwarded-Host"
        # contentTypeNosniff: true
        # browserXssFilter: true
        contentSecurityPolicy: 'frame-ancestors {{ env "HOST" }}'
        referrerPolicy: "same-origin"
