http:
  middlewares:
    authelia:
      forwardauth:
        address: 'http://authelia:9091/api/verify?rd=https://auth.{{ env "HOST" }}'
        trustForwardHeader: true
        authResponseHeaders: Remote-User,Remote-Groups,Remote-Name,Remote-Email
    iframe-headers:
      headers:
        contentSecurityPolicy: 'frame-ancestors {{ env "HOST" }}'
