http:
  routers:
    nextcloud:
      rule: "Host(`cloud.{{ env "TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_DOMAINS_MAIN" }}`)"
      entrypoints:
        - webSecure
      service: nextcloud
      tls:
        certresolver: ddnsResolver
      middlewares: nextcloud-chain

  services:
    nextcloud:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:11000" # Use the host's IP address if Traefik runs outside the host network

  middlewares:
    nextcloud-secure-headers:
      headers:
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        contentSecurityPolicy: "frame-ancestors {{ env "TRAEFIK_ENTRYPOINTS_WEBSECURE_HTTP_TLS_DOMAINS_MAIN" }}"

    https-redirect:
      redirectscheme:
        scheme: https

    nextcloud-chain:
      chain:
        middlewares:
          # - ... (e.g. rate limiting middleware)
          - https-redirect
          - nextcloud-secure-headers
